//tealium universal tag - utag.27 ut4.0.201605170801, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
$('.trackable').on('click',function(){var data_info=$(this).attr('data-info');data_info=JSON.parse(data_info);var xiti_type=data_info.event_type;var xiti_click=data_info.click_type;var xiti_label=data_info.event_name;var xiti_s2=data_info.event_s2;if(xiti_type==="click"){return xt_click(this,'C',xiti_s2,xiti_label,xiti_click);}
if(xiti_type==="load"){if(b.eventname==="ad_view::detail"){var x6="";if(xiti_label==="ad_reply::telephone::voir_le_numero"||xiti_label==="ad_reply::telephone::appeler_le_vendeur"){x6="ad_reply_phone";}
if(xiti_label==="ad_reply::telephone::envoyer_sms"){x6="ad_reply_sms";}
if(xiti_label==="ad_reply::email::demander_adresse"){x6="ad_reply_email";}
if(xiti_label==="ad_view::gerer_annonce::modifier"){x6="ad_action_modify";}
if(xiti_label==="ad_view::gerer_annonce::supprimer"){x6="ad_action_deletion";}
if(xiti_label==="ad_view::gerer_annonce::mettre_en_avant"){x6="ad_action_hightlight";}
if(xiti_label==="ad_view::gerer_annonce::remonter_en_tete_de_liste"){x6="ad_action_bump";}
var x="&x1=web_responsive-"+b.device+"&x2="+b.displaytype+"&x3="+b.pagetype+"&x4="+b.previouspage+"&x6="+x6+"&x7="+b.listid+"&x9="+b.cat_id+"&x10="+b.subcat_id+"&x11="+b.region+"&x12="+b.departement+"&x13="+b.ad_type+"&x14="+b.options+"&x15="+b.store_id_annonceur+"&x16="+b.offres+"&x17="+b.publish_date+"&x18="+b.last_update_date+"&x20="+b.city+"&x21="+b.boutique_id;var f="&f1="+b.listid+"&f2="+"!!pending_adid!!"+"&f3="+b.titre+"&f4="+b.cat_id+"&f5="+b.subcat_id+"&f6="+b.region+"&f7="+b.departement+"&f8="+b.city+"&f9="+b.ad_type+"&f10="+b.prix+"&f11="+b.nbphoto+"&f12="+b.options+"&f13="+b.store_id_annonceur+"&f14="+b.store_id+"&f15="+"!!pending_creationdate!!"+"&f16="+b.publish_date+"&f17="+b.last_update_date+"&f18="+b.offres+"&f19="+b.boutique_id;var stc="&stc={&quote;device&quote;:&quote;"+b.displaytype+"&quote;}";var stc="&stc="+encodeURIComponent("{\"device\":\""+b.displaytype+"\"}");return xt_click(this,'F',xiti_s2,xiti_label+""+x+""+f+""+stc);}
var stc="&stc="+encodeURIComponent("{\"device\":\""+b.displaytype+"\"}");return xt_click(this,'F',xiti_s2,xiti_label+stc);}});}};utag.o[loader].loader.LOAD(id);})("27","schibsted.leboncoin-responsive");}catch(error){utag.DB(error);}
